/**
 * GENERATED by scripts/logotype-variants.mjs — do not hand-edit.
 *   npm run logos:logotype
 *
 * Cap-height metrics for the logo marquee, derived from the committed SVGs by
 * measuring real path geometry in Chrome. Every number here is measured; the
 * decisions behind them (which subpaths are icon, which letter is the reference)
 * live in the RECORD table in that script, next to the category rule that
 * separates a lockup from an integrated mark.
 */

export interface LogotypeMetric {
  brand: string;
  /** lockup = icon removed · logotype = the word itself · integrated = mark spells part of the word */
  kind: "lockup" | "logotype" | "integrated";
  file: string;
  viewBox: string;
  /** capital-letter height in the file's own user units */
  capHeight: number;
  capRule: string;
  /** rendered height = --marquee-cap * heightRatio */
  heightRatio: number;
  aspect: number;
  /** baseline position as a fraction of the box, measured from its top */
  baselineRatio: number;
}

export const LOGOTYPE_METRICS = [
  {
    "brand": "adobe",
    "kind": "lockup",
    "file": "adobe-type.svg",
    "viewBox": "199.95 25.23 312.05 82.72",
    "capHeight": 75.36,
    "capRule": "cap height — flat capital A",
    "heightRatio": 1.0977,
    "aspect": 3.7724,
    "baselineRatio": 0.9865
  },
  {
    "brand": "atlassian",
    "kind": "lockup",
    "file": "atlassian-type.svg",
    "viewBox": "92.45 10.86 447.55 56.1",
    "capHeight": 54.44,
    "capRule": "cap height — flat capital T (S and O overshoot)",
    "heightRatio": 1.0305,
    "aspect": 7.9777,
    "baselineRatio": 0.9854
  },
  {
    "brand": "brilliant",
    "kind": "logotype",
    "file": "brilliant.svg",
    "viewBox": "0 0 114 27",
    "capHeight": 26.49,
    "capRule": "cap height — flat capital B",
    "heightRatio": 1.0193,
    "aspect": 4.2222,
    "baselineRatio": 0.9811
  },
  {
    "brand": "dropbox",
    "kind": "lockup",
    "file": "dropbox-type.svg",
    "viewBox": "142.19 33.35 307.29 70.99",
    "capHeight": 52.28,
    "capRule": "cap height — flat capital D",
    "heightRatio": 1.3579,
    "aspect": 4.3286,
    "baselineRatio": 0.7953
  },
  {
    "brand": "duolingo",
    "kind": "logotype",
    "file": "duolingo.svg",
    "viewBox": "0 0 400 94",
    "capHeight": 69.74,
    "capRule": "ascender height — flat l (the mark has no capitals)",
    "heightRatio": 1.3479,
    "aspect": 4.2553,
    "baselineRatio": 0.7419
  },
  {
    "brand": "figma",
    "kind": "logotype",
    "file": "figma-type.svg",
    "viewBox": "212 208 600 223",
    "capHeight": 177.65,
    "capRule": "cap height — flat capital F",
    "heightRatio": 1.2553,
    "aspect": 2.6906,
    "baselineRatio": 0.7966
  },
  {
    "brand": "google",
    "kind": "logotype",
    "file": "google.svg",
    "viewBox": "0 0 512 168",
    "capHeight": 121.85,
    "capRule": "ascender height — flat l (the only capital, G, is round and overshoots both lines)",
    "heightRatio": 1.3787,
    "aspect": 3.0476,
    "baselineRatio": 0.7546
  },
  {
    "brand": "linkedin",
    "kind": "integrated",
    "file": "linkedin.svg",
    "viewBox": "0 0 512 128",
    "capHeight": 91.43,
    "capRule": "cap height — flat capital L",
    "heightRatio": 1.4,
    "aspect": 4,
    "baselineRatio": 0.8571
  },
  {
    "brand": "notion",
    "kind": "lockup",
    "file": "notion-type.svg",
    "viewBox": "233.54 50.77 278.46 76.16",
    "capHeight": 68.85,
    "capRule": "cap height — flat capital N",
    "heightRatio": 1.1062,
    "aspect": 3.6563,
    "baselineRatio": 0.9861
  },
  {
    "brand": "pepsi",
    "kind": "lockup",
    "file": "pepsi-type.svg",
    "viewBox": "722.43 78.79 1268.9 452.7",
    "capHeight": 367.22,
    "capRule": "x-height of the i stem / 0.72 — no capitals and no ascenders",
    "heightRatio": 1.2328,
    "aspect": 2.803,
    "baselineRatio": 0.7822
  },
  {
    "brand": "philips",
    "kind": "logotype",
    "file": "philips.svg",
    "viewBox": "0 0 270 50",
    "capHeight": 48,
    "capRule": "cap height — flat capital H (P/S round off the baseline)",
    "heightRatio": 1.0417,
    "aspect": 5.4,
    "baselineRatio": 0.9798
  },
  {
    "brand": "samsung",
    "kind": "logotype",
    "file": "samsung.svg",
    "viewBox": "0 0 512 79",
    "capHeight": 73.19,
    "capRule": "cap height — flat capital A (S/U/G overshoot)",
    "heightRatio": 1.0794,
    "aspect": 6.481,
    "baselineRatio": 0.9561
  },
  {
    "brand": "sonos",
    "kind": "logotype",
    "file": "sonos-type.svg",
    "viewBox": "0 9.66 24 4.67",
    "capHeight": 4.61,
    "capRule": "cap height — flat capital N (O/S overshoot)",
    "heightRatio": 1.013,
    "aspect": 5.1392,
    "baselineRatio": 1
  },
  {
    "brand": "soundcloud",
    "kind": "lockup",
    "file": "soundcloud-type.svg",
    "viewBox": "14.54 120.03 225.62 24.01",
    "capHeight": 23.21,
    "capRule": "cap height — flat capital L (S/O/C overshoot)",
    "heightRatio": 1.0345,
    "aspect": 9.3969,
    "baselineRatio": 0.9833
  },
  {
    "brand": "spotify",
    "kind": "lockup",
    "file": "spotify-type.svg",
    "viewBox": "183.34 36.63 328.66 96.59",
    "capHeight": 74.06,
    "capRule": "cap height — capital S measured to the i-stem baseline",
    "heightRatio": 1.3042,
    "aspect": 3.4026,
    "baselineRatio": 0.8281
  }
] as const satisfies readonly LogotypeMetric[];

export const LOGOTYPE_METRIC_BY_BRAND: Record<string, LogotypeMetric> =
  Object.fromEntries(LOGOTYPE_METRICS.map((m) => [m.brand, m]));
