import type { CSSProperties, FunctionComponent, SVGProps } from "react";
/* LOGOTYPES, NOT LOCKUPS. Nine of these are `-type` variants generated by
   scripts/logotype-variants.mjs — the icon (or, for Figma and Sonos, the dead
   viewBox padding) removed, so that normalizing the strip to one cap height
   does not shrink the lockup wordmarks against the pure logotypes. Measured
   before the change, cap heights ran 3.5px to 21.9px: a 6.2x spread across what
   is meant to read as a single line of type.

   The six brands imported from their original file are already exactly their
   own logotype. LinkedIn is one of them deliberately — its `in` bug is
   separable geometry but inseparable spelling, so it is an INTEGRATED mark and
   stays whole. That category rule lives in the generator. */
import Spotify from "../assets/logos/spotify-type.svg?react";
import Notion from "../assets/logos/notion-type.svg?react";
import Google from "../assets/logos/google.svg?react";
import Duolingo from "../assets/logos/duolingo.svg?react";
import Samsung from "../assets/logos/samsung.svg?react";
import Figma from "../assets/logos/figma-type.svg?react";
import LinkedIn from "../assets/logos/linkedin.svg?react";
import Pepsi from "../assets/logos/pepsi-type.svg?react";
import Adobe from "../assets/logos/adobe-type.svg?react";
import Philips from "../assets/logos/philips.svg?react";
import Dropbox from "../assets/logos/dropbox-type.svg?react";
import Atlassian from "../assets/logos/atlassian-type.svg?react";
import SoundCloud from "../assets/logos/soundcloud-type.svg?react";
import Brilliant from "../assets/logos/brilliant.svg?react";
import Sonos from "../assets/logos/sonos-type.svg?react";
import { LOGOTYPE_METRIC_BY_BRAND } from "../assets/logos/logotypeMetrics";
import "./LogoMarquee.css";

interface Logo {
  name: string;
  /** Key into LOGOTYPE_METRIC_BY_BRAND — the measured cap-height record. */
  brand: string;
  Svg: FunctionComponent<SVGProps<SVGSVGElement>>;
  // Real Rive case-study URL: brands with a dedicated post link to it; the rest
  // point at the case-studies index. Keep the six named posts in sync with the
  // STORIES array in CaseStudies.tsx.
  href: string;
}

const CASE_STUDIES_INDEX = "https://rive.app/blog/case-studies";

// Ordered for rhythm — a deliberate mix of wide and compact marks.
const LOGOS: Logo[] = [
  {
    name: "Spotify",
    brand: "spotify",
    Svg: Spotify,
    href: "https://rive.app/blog/spotify-used-rive-for-spotify-wrapped-2025",
  },
  { name: "Notion", brand: "notion", Svg: Notion, href: CASE_STUDIES_INDEX },
  { name: "Google", brand: "google", Svg: Google, href: CASE_STUDIES_INDEX },
  {
    name: "Duolingo",
    brand: "duolingo",
    Svg: Duolingo,
    href: "https://rive.app/blog/duolingo-s-ai-powered-video-call-brings-lily-to-life",
  },
  { name: "Samsung", brand: "samsung", Svg: Samsung, href: CASE_STUDIES_INDEX },
  {
    name: "Figma",
    brand: "figma",
    Svg: Figma,
    href: "https://rive.app/blog/figma-s-new-homepage-is-full-of-rive-animations",
  },
  {
    name: "LinkedIn",
    brand: "linkedin",
    Svg: LinkedIn,
    href: "https://rive.app/blog/linkedin-year-in-review-2025-built-with-rive",
  },
  { name: "Pepsi", brand: "pepsi", Svg: Pepsi, href: CASE_STUDIES_INDEX },
  { name: "Adobe", brand: "adobe", Svg: Adobe, href: CASE_STUDIES_INDEX },
  { name: "Philips", brand: "philips", Svg: Philips, href: CASE_STUDIES_INDEX },
  {
    name: "Dropbox",
    brand: "dropbox",
    Svg: Dropbox,
    href: "https://rive.app/blog/dropbox-launches-interactive-brand-guidelines-site-using-rive",
  },
  {
    name: "Atlassian",
    brand: "atlassian",
    Svg: Atlassian,
    href: CASE_STUDIES_INDEX,
  },
  {
    name: "SoundCloud",
    brand: "soundcloud",
    Svg: SoundCloud,
    href: CASE_STUDIES_INDEX,
  },
  {
    name: "Brilliant",
    brand: "brilliant",
    Svg: Brilliant,
    href: "https://rive.app/blog/how-brilliant-org-motivates-learners-with-rive-animations",
  },
  { name: "Sonos", brand: "sonos", Svg: Sonos, href: CASE_STUDIES_INDEX },
];

function LogoGroup({ hidden }: { hidden?: boolean }) {
  return (
    <div className="marquee__group" aria-hidden={hidden || undefined}>
      {LOGOS.map(({ name, brand, Svg, href }) => {
        const metric = LOGOTYPE_METRIC_BY_BRAND[brand];
        return (
          <a
            key={name}
            className="marquee__logo"
            href={href}
            target="_blank"
            rel="noopener noreferrer"
            aria-label={hidden ? undefined : name}
            // The duplicated copy is decorative — keep it out of the tab order.
            tabIndex={hidden ? -1 : undefined}
            style={
              {
                /* Two measured numbers per brand, both derived from the
                   committed SVG rather than eyeballed: how tall the file has to
                   render for its capital to hit --marquee-cap, and where its
                   baseline sits inside that box so the strip can stand every
                   word on one line. */
                "--logo-k": metric.heightRatio,
                "--logo-baseline": metric.baselineRatio,
              } as CSSProperties
            }
          >
            <Svg className="marquee__svg" role="img" />
          </a>
        );
      })}
    </div>
  );
}

export function LogoMarquee() {
  return (
    <section className="marquee" aria-label="Companies building with Rive">
      <p className="marquee__label">
        TRUSTED IN PRODUCTS REACHING 2 BILLION PEOPLE
      </p>

      <div className="marquee__viewport">
        <div className="marquee__track">
          {/* Two back-to-back copies; translateX(-50%) advances exactly one. */}
          <LogoGroup />
          <LogoGroup hidden />
        </div>
      </div>
    </section>
  );
}

export default LogoMarquee;
